// Export formats for the viewer: STL (native), OBJ + 3MF (generated here),
// and STEP via the kernel's own exporter.
//
// generateSTEP is compiled into the kernel bundle but not re-exported from its
// public entry, and we deliberately don't modify kernel files (that would
// trigger its contribute-back license clause). The bundler tags functions with
// their original names (fn.name survives minification), so we locate it at
// runtime by name — with the STEP header marker as a fallback.
//
// generate3MF exists in the bundle too but only inside chunks that don't
// export it, so 3MF is generated here instead: a minimal spec-valid package
// (stored zip + 3dmodel.model XML) that slicers accept.

// Stamped into the 3MF's Application field — the honest answer to "what made
// this file".
const APP_VERSION = "0.1.7";

// OrcaSlicer greets any plain 3MF with "The 3MF file was generated by an old
// OrcaSlicer version, loading geometry data only" before it will show anything.
// It is a known Orca bug that hits every CAD exporter — Fusion 360 and Onshape
// included (OrcaSlicer #12434, #12950).
//
// Measured, the only thing it wants is a <metadata name="OrcaSlicer"> tag, and
// the accepted value is a WINDOW, not a floor:
//
//     absent / 1.0.0 / 2.0.0 / 2.1.0 / 2.2.0 / 2.3.0  ->  "old version"
//     2.4.0  (the exact installed build)              ->  clean
//     9.9.9                                           ->  "newer version"
//
// So no constant can be right for everyone: the file has to name the version of
// the Orca that opens it. A web page cannot know that. The DESKTOP app can —
// it reads the installed version out of the uninstall registry key — so it
// passes one in and gets a silent open. Everywhere else the tag is omitted and
// the file stays plainly spec-correct.

let kernelStep = null;

export async function loadGenerateSTEP() {
  if (kernelStep) return kernelStep;
  const mainUrl = "/node_modules/brep-io-kernel/dist-kernel/brep-kernel.js";
  const mainSrc = await (await fetch(mainUrl)).text();
  const chunkName = mainSrc.match(/\.\/(PartHistory-[\w-]+\.js)/)?.[1];
  if (!chunkName) throw new Error("Couldn't locate the kernel's exporter chunk.");
  const chunk = await import(`/node_modules/brep-io-kernel/dist-kernel/${chunkName}`);
  for (const v of Object.values(chunk)) {
    if (typeof v !== "function") continue;
    if (v.name === "generateSTEP" || String(v).includes("ISO-10303")) {
      kernelStep = v;
      return v;
    }
  }
  throw new Error("STEP exporter not found in this kernel version.");
}

// ---------------------------------------------------------------- mesh parse

function parseStlTriangles(stl) {
  const verts = [];
  const index = new Map();
  const tris = [];
  let tri = [];
  for (const m of stl.matchAll(/vertex\s+(-?[\d.eE+]+)\s+(-?[\d.eE+]+)\s+(-?[\d.eE+]+)/g)) {
    const key = `${m[1]},${m[2]},${m[3]}`;
    let i = index.get(key);
    if (i === undefined) {
      i = verts.length;
      index.set(key, i);
      verts.push([m[1], m[2], m[3]]);
    }
    tri.push(i);
    if (tri.length === 3) { tris.push(tri); tri = []; }
  }
  return { verts, tris };
}

// ---------------------------------------------------------------------- OBJ

export function stlToObj(stl, name = "brepcode-model") {
  const { verts, tris } = parseStlTriangles(stl);
  return `# BREPcode export\no ${name}\n`
    + verts.map((v) => `v ${v[0]} ${v[1]} ${v[2]}`).join("\n") + "\n"
    + tris.map((t) => `f ${t[0] + 1} ${t[1] + 1} ${t[2] + 1}`).join("\n") + "\n";
}

// ---------------------------------------------------------------- OBJ -> STL

// Minimal OBJ reader for imports: v/f lines, 1-based (and negative) indices,
// fan-triangulated polygons. Enough for meshes out of DCC tools and slicers.
export function objToStl(obj, name = "imported") {
  const verts = [];
  const out = [`solid ${name}`];
  for (const line of obj.split(/\r?\n/)) {
    const t = line.trim();
    if (t.startsWith("v ")) {
      const p = t.slice(2).trim().split(/\s+/).map(Number);
      verts.push(p);
    } else if (t.startsWith("f ")) {
      const idx = t.slice(2).trim().split(/\s+/)
        .map((tok) => parseInt(tok.split("/")[0], 10))
        .map((i) => (i < 0 ? verts.length + i : i - 1));
      for (let k = 1; k + 1 < idx.length; k++) {
        const tri = [verts[idx[0]], verts[idx[k]], verts[idx[k + 1]]];
        if (tri.some((v) => !v)) continue;
        out.push("facet normal 0 0 0", "outer loop");
        for (const v of tri) out.push(`vertex ${v[0]} ${v[1]} ${v[2]}`);
        out.push("endloop", "endfacet");
      }
    }
  }
  out.push(`endsolid ${name}`);
  return out.join("\n");
}

// ---------------------------------------------------------------------- 3MF

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(bytes) {
  let c = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) c = CRC_TABLE[(c ^ bytes[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

// A stored (uncompressed) zip — all any 3MF consumer needs.
function storedZip(entries) {
  const enc = new TextEncoder();
  const chunks = [], central = [];
  let offset = 0;
  const u16 = (n) => new Uint8Array([n & 255, (n >> 8) & 255]);
  const u32 = (n) => new Uint8Array([n & 255, (n >> 8) & 255, (n >> 16) & 255, (n >>> 24) & 255]);

  for (const [name, content] of entries) {
    const nameB = enc.encode(name);
    const data = typeof content === "string" ? enc.encode(content) : content;
    const crc = crc32(data);
    const head = [u32(0x04034b50), u16(20), u16(0), u16(0), u16(0), u16(0),
      u32(crc), u32(data.length), u32(data.length), u16(nameB.length), u16(0)];
    central.push({ nameB, crc, size: data.length, offset });
    for (const p of head) { chunks.push(p); offset += p.length; }
    chunks.push(nameB, data);
    offset += nameB.length + data.length;
  }

  const cdStart = offset;
  for (const e of central) {
    const rec = [u32(0x02014b50), u16(20), u16(20), u16(0), u16(0), u16(0), u16(0),
      u32(e.crc), u32(e.size), u32(e.size), u16(e.nameB.length), u16(0), u16(0),
      u16(0), u16(0), u32(0), u32(e.offset)];
    for (const p of rec) { chunks.push(p); offset += p.length; }
    chunks.push(e.nameB);
    offset += e.nameB.length;
  }
  chunks.push(u32(0x06054b50), u16(0), u16(0), u16(central.length), u16(central.length),
    u32(offset - cdStart), u32(cdStart), u16(0));

  const total = chunks.reduce((n, c) => n + c.length, 0);
  const out = new Uint8Array(total);
  let p = 0;
  for (const c of chunks) { out.set(c, p); p += c.length; }
  return out;
}

// Colour-aware 3MF. `groups` is [{ verts:[[x,y,z],…], tris:[[a,b,c],…], color:"#rrggbb" }].
// All geometry lands in ONE object; each triangle carries a p1 index into a
// <m:colorgroup> via the 3MF materials extension. Bambu Studio / PrusaSlicer /
// OrcaSlicer read that as per-face paint and auto-assign a filament per colour —
// so an embossed label or code prints in its own colour on a multi-material
// printer. Consumers that ignore the extension still get correct geometry.
export function colored3MF(groups, name = "brepcode-model", opts = {}) {
  const palette = [];                       // distinct colours, in first-seen order
  const idxOf = (c) => {
    const hex = (c || "#cccccc").toUpperCase();
    let i = palette.indexOf(hex);
    if (i < 0) { i = palette.length; palette.push(hex); }
    return i;
  };

  const verts = [];
  const tris = [];                          // [v1, v2, v3, colorIndex]
  for (const g of groups) {
    const base = verts.length;
    const ci = idxOf(g.color);
    for (const v of g.verts) verts.push(v);
    for (const t of g.tris) tris.push([base + t[0], base + t[1], base + t[2], ci]);
  }
  if (!tris.length) return stlTo3MF("", name, opts);

  const M = "http://schemas.microsoft.com/3dmanufacturing/material/2015/02";
  const colorgroup = `  <m:colorgroup id="2">
${palette.map((c) => `   <m:color color="${c}"/>`).join("\n")}
  </m:colorgroup>`;
  const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:m="${M}">
 <resources>
${colorgroup}
  <object id="1" type="model" name="${name}" pid="2" pindex="0">
   <mesh>
    <vertices>
${verts.map((v) => `     <vertex x="${v[0]}" y="${v[1]}" z="${v[2]}"/>`).join("\n")}
    </vertices>
    <triangles>
${tris.map((t) => `     <triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}" p1="${t[3]}"/>`).join("\n")}
    </triangles>
   </mesh>
  </object>
 </resources>
 <build>
  <item objectid="1"/>
 </build>
</model>
`;
  return threeMfPackage(model, name, opts.source);
}

// Where the parametric source rides along inside an exported file. A mesh is a
// dead end — once a part leaves as triangles the recipe that made it is gone,
// and "I printed this a year ago and want it 3mm taller" means starting over.
// 3MF is a zip, so the source travels as its own plain-text part: readable with
// any unzip tool, ignored by every slicer, and enough to reopen the part as
// editable code. Keep the part name and marker stable — older files must keep
// loading.
export const SOURCE_PART = "Metadata/BREPcode.source.js";
export const SOURCE_MARKER = "BREPCODE-SOURCE-V1";

const sourceHeader = (name) =>
  `// ${SOURCE_MARKER}\n`
  + `// The BREPcode that generated "${name}". Paste it into BREPcode.com to get\n`
  + `// the editable, parametric model back — or just read it to see how it was made.\n`
  + `// Exported by BREPcode-${APP_VERSION}.\n\n`;

// The OPC wrapper both 3MF writers share. Every part in the package needs a
// declared content type, so the source brings its own Default. Slicers read
// 3D/3dmodel.model and ignore the rest — Bambu and Orca both ship extra
// Metadata/ parts of their own, so this is a well-trodden path, not a hack.
function threeMfPackage(model, name, code) {
  const source = code ? String(code).trim() : "";
  return storedZip([
    ["[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
 <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
 <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
${source ? ` <Default Extension="js" ContentType="text/javascript"/>\n` : ""}</Types>
`],
    ["_rels/.rels", `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
 <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
`],
    ["3D/3dmodel.model", model],
    ...(source ? [[SOURCE_PART, sourceHeader(name) + source + "\n"]] : []),
  ]);
}

// ---------------------------------------------------------------- .bcode
//
// The project file: the one export that is the MODEL rather than a picture of
// it. Everything else here throws the recipe away and keeps the triangles;
// this keeps the recipe and can regenerate the triangles at any size.
//
// It exists because nothing in BREPcode saved your work. Theme, material,
// grid, model name and AI settings were all persisted — the CODE never was.
// Close the tab and it was gone.
//
// Deliberately PLAIN TEXT, not JSON. The source sits at the top exactly as you
// wrote it, so the file opens in Notepad and is directly editable, diffs
// cleanly in git, and can be pasted straight into the app. The scene and the
// undo history ride underneath in a block comment, which the app reads and
// everything else ignores. Hand-edit the source, mangle the comment, delete it
// entirely — the file still loads, because the source is the part that matters
// and the rest is decoration.
export const SCENE_OPEN = "/* BREPCODE-SCENE-V1";
export const SCENE_CLOSE = "BREPCODE-SCENE-END */";

// Undo history is capped: the in-app stack holds 200 full copies of the source,
// which on a real model is megabytes of near-identical text for something
// nobody scrolls back through. The most recent states are the useful ones.
export const HISTORY_KEEP = 40;

export function bcodeFile(source, meta = {}) {
  const src = String(source || "").trim();
  const name = String(meta.name || "brepcode-model").replace(/[\r\n]/g, " ");
  const scene = {};
  if (meta.scene) scene.scene = meta.scene;
  if (Array.isArray(meta.history) && meta.history.length) {
    scene.history = meta.history.slice(-HISTORY_KEEP).map((h) => String(h));
  }

  let out = `// ${SOURCE_MARKER}\n`
    + `// "${name}" — a BREPcode model, saved by BREPcode-${APP_VERSION}.\n`
    + `// This is plain text: edit the model below in any editor, or paste it\n`
    + `// into BREPcode.com. Opening this file in BREPcode restores it exactly.\n\n`
    + `${src}\n`;
  if (Object.keys(scene).length) {
    // Guard the delimiters: source containing the closing token would end the
    // comment early and spill JSON into the model. It cannot happen from the
    // source side (it sits above), but a scene value could carry anything.
    const json = JSON.stringify(scene, null, 1).split("*/").join("*\\/");
    out += `\n${SCENE_OPEN}\n${json}\n${SCENE_CLOSE}\n`;
  }
  return out;
}

// Split a .bcode file back into its parts. A file that is nothing but bare
// BREPcode — someone's hand-written model, or ours with the comment deleted —
// still parses: you get the source and no scene, which is the correct reading.
export function parseBcodeFile(text) {
  const t = String(text || "").replace(/^﻿/, "");
  let scene = null;
  let body = t;

  const open = t.indexOf(SCENE_OPEN);
  if (open >= 0) {
    // Cut the body at the marker whether or not the block ever closes. A file
    // truncated mid-write — interrupted download, full disk — has an opening
    // marker and no end, and keeping the whole text would have dropped raw JSON
    // into the editor as if it were part of the model.
    body = t.slice(0, open);
    const close = t.indexOf(SCENE_CLOSE, open);
    if (close > open) {
      try {
        scene = JSON.parse(t.slice(open + SCENE_OPEN.length, close).split("*\\/").join("*/"));
      } catch { scene = null; }      // a corrupted block must not cost the source
    }
  }
  return {
    source: stripSourceHeader(body),
    scene: scene?.scene ?? null,
    history: Array.isArray(scene?.history) ? scene.history : [],
  };
}

// The same idea for STL, which has no container at all — the source goes after
// `endsolid`, where a well-behaved reader stops.
//
// It is BASE64, not plain text, and that is deliberate: three.js's ASCII STL
// loader regex-scans the WHOLE file for `facet normal` blocks rather than
// stopping at endsolid. Source that happened to contain those words — a
// comment, a string, one of our own generated-STL examples — would inject
// phantom triangles into anything that reimported it. Base64 cannot collide
// with the grammar. The plain-English header above it says what it is.
export function stlWithSource(stl, code) {
  const source = code ? String(code).trim() : "";
  if (!source) return stl;
  const b64 = btoa(unescape(encodeURIComponent(source)));
  return `${stl.trimEnd()}\n${SOURCE_MARKER}\n`
    + "The BREPcode that generated this part, as base64 of UTF-8. Decode it and\n"
    + "paste it into BREPcode.com to get the editable, parametric model back.\n"
    + `${(b64.match(/.{1,76}/g) || []).join("\n")}\nEND-${SOURCE_MARKER}\n`;
}

// Take our own header off the 3MF source part, and nothing else. Stripping
// every `//` line instead — the obvious shortcut — silently ate the author's
// own comments on the way back in, which is a worse loss than the header.
export function stripSourceHeader(text) {
  const t = String(text || "").replace(/^﻿/, "");
  if (!t.startsWith(`// ${SOURCE_MARKER}`)) return t.trim();
  const gap = t.indexOf("\n\n");
  return (gap < 0 ? "" : t.slice(gap + 2)).trim();
}

// Pull it back out of an STL. Returns "" when there is none, which is the
// normal case for a file from anywhere else.
export function extractSourceFromStl(text) {
  const m = new RegExp(
    `${SOURCE_MARKER}\\n[\\s\\S]*?\\n((?:[A-Za-z0-9+/=]+\\n)+)END-${SOURCE_MARKER}`).exec(text);
  if (!m) return "";
  try { return decodeURIComponent(escape(atob(m[1].replace(/\s/g, "")))); }
  catch { return ""; }
}

export function stlTo3MF(stl, name = "brepcode-model", opts = {}) {
  const { verts, tris } = parseStlTriangles(stl);
  // Core-spec metadata, so anything reading this file knows where it came from.
  // Our 3MF used to declare nothing at all, which is simply a gap.
  //
  // What this deliberately does NOT do is claim to be a slicer project.
  // OrcaSlicer greets a bare 3MF with "generated by an old OrcaSlicer version,
  // loading geometry data only", and the tempting fix — adding its
  // `BambuStudio:3mfVersion` marker — is a trap: it makes Orca take the Bambu
  // project path, then hunt for the per-object settings, plate thumbnails and
  // slice info that a real project carries. Measured, the file went from
  // loading in about 30 seconds to not loading at all. The message is also
  // accurate: we export geometry, and have no print settings to give it.
  const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
 <metadata name="Application">BREPcode-${APP_VERSION}</metadata>
${opts.orcaVersion ? `
 <metadata name="OrcaSlicer">${opts.orcaVersion}</metadata>` : ""} <metadata name="Title">${name}</metadata>
 <resources>
  <object id="1" type="model" name="${name}">
   <mesh>
    <vertices>
${verts.map((v) => `     <vertex x="${v[0]}" y="${v[1]}" z="${v[2]}"/>`).join("\n")}
    </vertices>
    <triangles>
${tris.map((t) => `     <triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}"/>`).join("\n")}
    </triangles>
   </mesh>
  </object>
 </resources>
 <build>
  <item objectid="1"/>
 </build>
</model>
`;
  return threeMfPackage(model, name, opts.source);
}
