// Export formats for the viewer: STL (native), OBJ + 3MF (generated here),
// and STEP via the kernel's own exporter.
//
// generateSTEP is compiled into the kernel bundle but not re-exported from its
// public entry, and we deliberately don't modify kernel files (that would
// trigger its contribute-back license clause). The bundler tags functions with
// their original names (fn.name survives minification), so we locate it at
// runtime by name — with the STEP header marker as a fallback.
//
// generate3MF exists in the bundle too but only inside chunks that don't
// export it, so 3MF is generated here instead: a minimal spec-valid package
// (stored zip + 3dmodel.model XML) that slicers accept.

// Stamped into the 3MF's Application field — the honest answer to "what made
// this file".
const APP_VERSION = "0.2.2";

// A note on OrcaSlicer, because this cost real time and the conclusion is the
// opposite of where it started.
//
// The belief was that Orca greets any plain 3MF with "generated by an old
// OrcaSlicer version, loading geometry data only", and that the cure was to
// declare <metadata name="OrcaSlicer"> naming the installed version. So the
// desktop app learned to detect that version and stamp it in.
//
// Tested properly, with two files opened side by side in a real Orca:
//
//     no OrcaSlicer metadata at all  ->  opens silently
//     the exact installed version    ->  opens silently
//     a version that is too high     ->  "Newer 3MF version" dialog
//
// A plain 3MF is FINE. The tag is what invites the version comparison, so
// emitting it could only ever break even — and when the detected version was
// wrong it produced the worse dialog of the two. We were creating the problem
// we were then trying to solve.
//
// So we emit no slicer-specific metadata, the file stays plainly spec-correct,
// and a download from the website behaves exactly like one from the desktop
// app. Please do not add the tag back without a file that demonstrably needs
// it.

let kernelStep = null;

export async function loadGenerateSTEP() {
  if (kernelStep) return kernelStep;
  const mainUrl = "/node_modules/brep-io-kernel/dist-kernel/brep-kernel.js";
  const mainSrc = await (await fetch(mainUrl)).text();
  const chunkName = mainSrc.match(/\.\/(PartHistory-[\w-]+\.js)/)?.[1];
  if (!chunkName) throw new Error("Couldn't locate the kernel's exporter chunk.");
  const chunk = await import(`/node_modules/brep-io-kernel/dist-kernel/${chunkName}`);
  for (const v of Object.values(chunk)) {
    if (typeof v !== "function") continue;
    if (v.name === "generateSTEP" || String(v).includes("ISO-10303")) {
      kernelStep = v;
      return v;
    }
  }
  throw new Error("STEP exporter not found in this kernel version.");
}

// ---------------------------------------------------------------- mesh parse

function parseStlTriangles(stl) {
  const verts = [];
  const index = new Map();
  const tris = [];
  let tri = [];
  for (const m of stl.matchAll(/vertex\s+(-?[\d.eE+]+)\s+(-?[\d.eE+]+)\s+(-?[\d.eE+]+)/g)) {
    const key = `${m[1]},${m[2]},${m[3]}`;
    let i = index.get(key);
    if (i === undefined) {
      i = verts.length;
      index.set(key, i);
      verts.push([m[1], m[2], m[3]]);
    }
    tri.push(i);
    if (tri.length === 3) { tris.push(tri); tri = []; }
  }
  return { verts, tris };
}

// ---------------------------------------------------------------------- OBJ

export function stlToObj(stl, name = "brepcode-model") {
  const { verts, tris } = parseStlTriangles(stl);
  return `# BREPcode export\no ${name}\n`
    + verts.map((v) => `v ${v[0]} ${v[1]} ${v[2]}`).join("\n") + "\n"
    + tris.map((t) => `f ${t[0] + 1} ${t[1] + 1} ${t[2] + 1}`).join("\n") + "\n";
}

// ---------------------------------------------------------------- OBJ -> STL

// Minimal OBJ reader for imports: v/f lines, 1-based (and negative) indices,
// fan-triangulated polygons. Enough for meshes out of DCC tools and slicers.
export function objToStl(obj, name = "imported") {
  const verts = [];
  const out = [`solid ${name}`];
  for (const line of obj.split(/\r?\n/)) {
    const t = line.trim();
    if (t.startsWith("v ")) {
      const p = t.slice(2).trim().split(/\s+/).map(Number);
      verts.push(p);
    } else if (t.startsWith("f ")) {
      const idx = t.slice(2).trim().split(/\s+/)
        .map((tok) => parseInt(tok.split("/")[0], 10))
        .map((i) => (i < 0 ? verts.length + i : i - 1));
      for (let k = 1; k + 1 < idx.length; k++) {
        const tri = [verts[idx[0]], verts[idx[k]], verts[idx[k + 1]]];
        if (tri.some((v) => !v)) continue;
        out.push("facet normal 0 0 0", "outer loop");
        for (const v of tri) out.push(`vertex ${v[0]} ${v[1]} ${v[2]}`);
        out.push("endloop", "endfacet");
      }
    }
  }
  out.push(`endsolid ${name}`);
  return out.join("\n");
}

// ---------------------------------------------------------------------- 3MF

const CRC_TABLE = (() => {
  const t = new Uint32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c >>> 0;
  }
  return t;
})();

function crc32(bytes) {
  let c = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) c = CRC_TABLE[(c ^ bytes[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

// A stored (uncompressed) zip — all any 3MF consumer needs.
function storedZip(entries) {
  const enc = new TextEncoder();
  const chunks = [], central = [];
  let offset = 0;
  const u16 = (n) => new Uint8Array([n & 255, (n >> 8) & 255]);
  const u32 = (n) => new Uint8Array([n & 255, (n >> 8) & 255, (n >> 16) & 255, (n >>> 24) & 255]);

  for (const [name, content] of entries) {
    const nameB = enc.encode(name);
    const data = typeof content === "string" ? enc.encode(content) : content;
    const crc = crc32(data);
    const head = [u32(0x04034b50), u16(20), u16(0), u16(0), u16(0), u16(0),
      u32(crc), u32(data.length), u32(data.length), u16(nameB.length), u16(0)];
    central.push({ nameB, crc, size: data.length, offset });
    for (const p of head) { chunks.push(p); offset += p.length; }
    chunks.push(nameB, data);
    offset += nameB.length + data.length;
  }

  const cdStart = offset;
  for (const e of central) {
    const rec = [u32(0x02014b50), u16(20), u16(20), u16(0), u16(0), u16(0), u16(0),
      u32(e.crc), u32(e.size), u32(e.size), u16(e.nameB.length), u16(0), u16(0),
      u16(0), u16(0), u32(0), u32(e.offset)];
    for (const p of rec) { chunks.push(p); offset += p.length; }
    chunks.push(e.nameB);
    offset += e.nameB.length;
  }
  chunks.push(u32(0x06054b50), u16(0), u16(0), u16(central.length), u16(central.length),
    u32(offset - cdStart), u32(cdStart), u16(0));

  const total = chunks.reduce((n, c) => n + c.length, 0);
  const out = new Uint8Array(total);
  let p = 0;
  for (const c of chunks) { out.set(c, p); p += c.length; }
  return out;
}

// Colour-aware 3MF. `groups` is [{ verts:[[x,y,z],…], tris:[[a,b,c],…], color:"#rrggbb" }].
// All geometry lands in ONE object; each triangle carries a p1 index into a
// <m:colorgroup> via the 3MF materials extension. Bambu Studio / PrusaSlicer /
// OrcaSlicer read that as per-face paint and auto-assign a filament per colour —
// so an embossed label or code prints in its own colour on a multi-material
// printer. Consumers that ignore the extension still get correct geometry.
// Colour that a slicer actually honours.
//
// The obvious reading of the spec — one object, a <m:colorgroup>, a colour
// index per triangle — is what this used to do, and OrcaSlicer ignored it
// completely: the model arrived in one colour. Taking apart a Bambu 4-colour
// Benchy that DOES work showed why. There is no colorgroup in it anywhere.
// Colour is per PART:
//
//   3D/3dmodel.model            one object per colour, plus an assembly object
//                               whose <components> reference them
//   Metadata/model_settings.config
//                               <part id="N"> per component, each carrying
//                               <metadata key="extruder" value="k"/>
//
// The extruder number is the colour. So each distinct colour becomes its own
// part, and the slicer assigns it a filament.
//
// What that Benchy ALSO carries, and this deliberately does not: a 57KB
// project_settings.config of printer presets, a BambuStudio:3mfVersion marker,
// plate thumbnails, slice info. Opening it produced four dialogs in a row —
// "Customized Preset", "configuration from a newer version", "BambuStudio
// Project". None of that is needed to carry colour, and every piece of it is
// another version to be wrong about. This writes the geometry, the parts, and
// the extruder numbers. Nothing else.
//
// The colorgroup stays too. It costs a few bytes, it is the spec-correct answer,
// and tools that are not Orca do read it.
// ------------------------------------------------------------ plate placing
//
// A slicer's build plate has its origin at the FRONT-LEFT corner, and BREPcode
// models are built around 0,0 — so a 3MF exported as-is opens in the corner
// with half the part hanging off the plate. (STL doesn't have this problem:
// with no position information at all, slicers centre it themselves.)
//
// The offset is BAKED INTO THE COORDINATES rather than written as an <item>
// transform. The transform is the tidier answer and the spec supports it, but
// it is also something a slicer can quietly ignore or reset on import, and the
// whole point here is that the part lands where we say. Baked geometry cannot
// be ignored.
//
// The plate defaults to 256 × 256 — Bambu X1/P1/A1 and Orca's stock profile.
// Pass opts.plate = { x, y } for anything else.
export const DEFAULT_PLATE = { x: 256, y: 256 };

// Centre the model's footprint on the plate and stand it on the bed.
// plate === null means "leave the coordinates exactly as modelled".
export function plateOffset(bounds, plate = DEFAULT_PLATE) {
  if (plate === null) return [0, 0, 0];
  const px = Number(plate?.x) > 0 ? Number(plate.x) : DEFAULT_PLATE.x;
  const py = Number(plate?.y) > 0 ? Number(plate.y) : DEFAULT_PLATE.y;
  return [
    px / 2 - (bounds.minX + bounds.maxX) / 2,
    py / 2 - (bounds.minY + bounds.maxY) / 2,
    -bounds.minZ,                    // a part that starts below the bed is lifted onto it
  ];
}

function boundsOf(points) {
  const b = { minX: Infinity, minY: Infinity, minZ: Infinity, maxX: -Infinity, maxY: -Infinity, maxZ: -Infinity };
  for (const p of points) {
    const x = +p[0], y = +p[1], z = +p[2];
    if (x < b.minX) b.minX = x; if (x > b.maxX) b.maxX = x;
    if (y < b.minY) b.minY = y; if (y > b.maxY) b.maxY = y;
    if (z < b.minZ) b.minZ = z; if (z > b.maxZ) b.maxZ = z;
  }
  return b;
}

export function colored3MF(groups, name = "brepcode-model", opts = {}) {
  const palette = [];                       // distinct colours, in first-seen order
  const byColour = new Map();               // colour -> merged {verts, tris}
  for (const g of groups) {
    const hex = (g.color || "#cccccc").toUpperCase();
    if (!palette.includes(hex)) palette.push(hex);
    let bucket = byColour.get(hex);
    if (!bucket) { bucket = { verts: [], tris: [], index: new Map() }; byColour.set(hex, bucket); }
    // WELD inside the colour. The groups come from the on-screen meshes, which
    // are one mesh per FACE, so every point on a face boundary arrives once per
    // face touching it. Written as-is, triangles that share an edge reference
    // DIFFERENT vertices — a surface that looks right and is topologically full
    // of cracks. A real export came back 6585 vertices for 1719 distinct
    // positions and would not reimport: "non-manifold".
    const idOf = (v) => {
      const k = `${+(+v[0]).toFixed(5)},${+(+v[1]).toFixed(5)},${+(+v[2]).toFixed(5)}`;
      let i = bucket.index.get(k);
      if (i === undefined) { i = bucket.verts.length; bucket.index.set(k, i); bucket.verts.push(v); }
      return i;
    };
    const local = g.verts.map(idOf);
    for (const t of g.tris) {
      const [a, b, c] = [local[t[0]], local[t[1]], local[t[2]]];
      if (a === b || b === c || a === c) continue;      // collapsed by the weld
      bucket.tris.push([a, b, c]);
    }
  }

  const used = palette.filter((hex) => byColour.get(hex)?.tris.length);
  if (!used.length) return stlTo3MF("", name, opts);

  // One offset for the WHOLE assembly, measured across every colour — moving
  // each colour to its own centre would take the model apart.
  const [ox, oy, oz] = plateOffset(
    boundsOf(used.flatMap((hex) => byColour.get(hex).verts)), opts.plate);

  const M = "http://schemas.microsoft.com/3dmanufacturing/material/2015/02";
  const COLOURS_ID = 1;
  const firstObject = 2;                                   // ids 2 … 2+n-1
  const assemblyId = firstObject + used.length;

  const objects = used.map((hex, i) => {
    const { verts, tris } = byColour.get(hex);
    return `  <object id="${firstObject + i}" type="model" name="${name} — ${hex}" pid="${COLOURS_ID}" pindex="${i}">
   <mesh>
    <vertices>
${verts.map((v) => `     <vertex x="${+(+v[0] + ox).toFixed(5)}" y="${+(+v[1] + oy).toFixed(5)}" z="${+(+v[2] + oz).toFixed(5)}"/>`).join("\n")}
    </vertices>
    <triangles>
${tris.map((t) => `     <triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}"/>`).join("\n")}
    </triangles>
   </mesh>
  </object>`;
  }).join("\n");

  const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:m="${M}">
 <metadata name="Application">BREPcode-${APP_VERSION}</metadata>
 <metadata name="Title">${name}</metadata>
 <resources>
  <m:colorgroup id="${COLOURS_ID}">
${used.map((hex) => `   <m:color color="${hex}"/>`).join("\n")}
  </m:colorgroup>
${objects}
  <object id="${assemblyId}" type="model" name="${name}">
   <components>
${used.map((_, i) => `    <component objectid="${firstObject + i}"/>`).join("\n")}
   </components>
  </object>
 </resources>
 <build>
  <item objectid="${assemblyId}"/>
 </build>
</model>
`;

  // One <part> per component, in the same order, each naming its extruder.
  // part id matches the component's objectid — that is the mapping the working
  // file uses.
  const settings = `<?xml version="1.0" encoding="UTF-8"?>
<config>
  <object id="${assemblyId}">
    <metadata key="name" value="${name}"/>
    <metadata key="extruder" value="1"/>
${used.map((hex, i) => `    <part id="${firstObject + i}" subtype="normal_part">
      <metadata key="name" value="${name} — ${hex}"/>
      <metadata key="extruder" value="${i + 1}"/>
    </part>`).join("\n")}
  </object>
</config>
`;
  // The other half of the colour story: model_settings says which EXTRUDER
  // each part uses, project_settings says what colour each extruder holds.
  // We wrote only the first half — so our own coloured exports re-imported
  // GREY (and slicers showed default filament colours). Both halves now ship.
  const project = `{\n  "filament_colour": [${used.map((hex) => `"${hex}"`).join(", ")}]\n}\n`;
  return threeMfPackage(model, name, opts.source, [
    ["Metadata/model_settings.config", settings],
    ["Metadata/project_settings.config", project],
  ]);
}

// ------------------------------------------------- parts laid out on plates
//
// The normal 3MF keeps the assembly ASSEMBLED — a cap exports sitting on its
// jar, because that is what the model says. For printing you usually want the
// opposite: every physically separate piece side by side on the bed. "Part"
// here means a connected component of the mesh — decided by geometry, not by
// colour or feature, because a two-colour cap is one part and two cubes of the
// same colour are two.

// Split colour groups into connected parts. Vertices weld across group
// boundaries (a part's colours meet at coincident vertices), then triangles
// union their corners; each surviving root is one physical piece.
export function splitConnectedParts(groups) {
  const key2id = new Map();
  const parent = [];
  const find = (a) => { while (parent[a] !== a) { parent[a] = parent[parent[a]]; a = parent[a]; } return a; };
  const union = (a, b) => { const ra = find(a), rb = find(b); if (ra !== rb) parent[rb] = ra; };
  const idOf = (v) => {
    const k = `${+(+v[0]).toFixed(4)},${+(+v[1]).toFixed(4)},${+(+v[2]).toFixed(4)}`;
    let i = key2id.get(k);
    if (i === undefined) { i = parent.length; key2id.set(k, i); parent.push(i); }
    return i;
  };
  const welded = groups.map((g) => {
    const ids = g.verts.map(idOf);
    for (const t of g.tris) { union(ids[t[0]], ids[t[1]]); union(ids[t[1]], ids[t[2]]); }
    return ids;
  });
  // root -> part; each part keeps per-colour groups with local indexing
  const parts = new Map();
  groups.forEach((g, gi) => {
    const ids = welded[gi];
    for (const t of g.tris) {
      const root = find(ids[t[0]]);
      let part = parts.get(root);
      if (!part) { part = { colours: new Map() }; parts.set(root, part); }
      let sub = part.colours.get(g.color);
      if (!sub) { sub = { color: g.color, verts: [], tris: [], local: new Map() }; part.colours.set(g.color, sub); }
      const li = t.map((vi) => {
        let l = sub.local.get(vi);
        if (l === undefined) { l = sub.verts.length; sub.local.set(vi, l); sub.verts.push(g.verts[vi]); }
        return l;
      });
      sub.tris.push(li);
    }
  });
  return [...parts.values()].map((p) => ({
    groups: [...p.colours.values()].map(({ color, verts, tris }) => ({ color, verts, tris })),
  }));
}

// Shelf-pack the parts onto plates. Every part stands on the bed (its own
// minZ -> 0 — in an assembly the cap floats above the jar, and printed alone
// it must not). Rows fill front-to-back; a part that no longer fits starts the
// next plate, so the return is ONE LAYOUT PER PLATE. gap is air between parts.
export function layoutOnPlates(parts, plate = DEFAULT_PLATE, gap = 8) {
  const px = Number(plate?.x) > 0 ? Number(plate.x) : DEFAULT_PLATE.x;
  const py = Number(plate?.y) > 0 ? Number(plate.y) : DEFAULT_PLATE.y;
  const sized = parts.map((part) => {
    const b = boundsOf(part.groups.flatMap((g) => g.verts));
    return { part, b, w: b.maxX - b.minX, d: b.maxY - b.minY };
  }).sort((a, r) => Math.max(r.w, r.d) - Math.max(a.w, a.d));   // big first packs tighter

  const plates = [];
  let cur = null;
  const open = () => { cur = { placed: [], x: 0, y: 0, rowDepth: 0 }; plates.push(cur); };
  open();
  for (const s of sized) {
    if (cur.x > 0 && cur.x + s.w > px) {              // row full -> next row
      cur.x = 0; cur.y += cur.rowDepth + gap; cur.rowDepth = 0;
    }
    if (cur.y + s.d > py && cur.placed.length) {      // plate full -> next plate
      open();
    }
    cur.placed.push({
      part: s.part,
      dx: cur.x - s.b.minX, dy: cur.y - s.b.minY, dz: -s.b.minZ,
      w: s.w, d: s.d,
    });
    cur.x += s.w + gap;
    cur.rowDepth = Math.max(cur.rowDepth, s.d);
  }
  // centre each plate's occupied footprint, so the arrangement sits in the
  // middle of the bed rather than crowding the front-left corner. dx/dy put a
  // part's minX/minY at its slot, so slot + footprint is its far edge.
  for (const pl of plates) {
    const mx = Math.max(...pl.placed.map((p) => p.dx + boundsOf(p.part.groups.flatMap((g) => g.verts)).maxX));
    const my = Math.max(...pl.placed.map((p) => p.dy + boundsOf(p.part.groups.flatMap((g) => g.verts)).maxY));
    const sx = (px - mx) / 2, sy = (py - my) / 2;
    for (const p of pl.placed) { p.dx += sx; p.dy += sy; }
  }
  return plates.map((pl) => pl.placed.map(({ part, dx, dy, dz }) => ({ part, dx, dy, dz })));
}

// The laid-out export itself: one 3MF PER PLATE, each part its own object (its
// colours as sub-objects referenced by a per-part assembly), so the slicer
// sees N movable parts, each already standing where it should print. Returns
// [{ suffix, bytes }] — one entry per plate.
export function partsPlate3MF(groups, name = "brepcode-model", opts = {}) {
  const parts = splitConnectedParts(groups);
  if (!parts.length) return [];
  const plate = opts.plate === null ? DEFAULT_PLATE : (opts.plate ?? DEFAULT_PLATE);
  const plates = layoutOnPlates(parts, plate, opts.gap ?? 8);
  const M = "http://schemas.microsoft.com/3dmanufacturing/material/2015/02";

  return plates.map((placed, pi) => {
    const palette = [];
    for (const { part } of placed) for (const g of part.groups) {
      const hex = (g.color || "#cccccc").toUpperCase();
      if (!palette.includes(hex)) palette.push(hex);
    }
    const COLOURS_ID = 1;
    let nextId = 2;
    const objects = [], items = [], settings = [];
    placed.forEach(({ part, dx, dy, dz }, idx) => {
      const colourIds = part.groups.map((g) => {
        const hex = (g.color || "#cccccc").toUpperCase();
        const id = nextId++;
        objects.push(`  <object id="${id}" type="model" name="${name} — part ${idx + 1} — ${hex}" pid="${COLOURS_ID}" pindex="${palette.indexOf(hex)}">
   <mesh>
    <vertices>
${g.verts.map((v) => `     <vertex x="${+(+v[0] + dx).toFixed(5)}" y="${+(+v[1] + dy).toFixed(5)}" z="${+(+v[2] + dz).toFixed(5)}"/>`).join("\n")}
    </vertices>
    <triangles>
${g.tris.map((t) => `     <triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}"/>`).join("\n")}
    </triangles>
   </mesh>
  </object>`);
        return { id, hex };
      });
      const partId = nextId++;
      objects.push(`  <object id="${partId}" type="model" name="${name} — part ${idx + 1}">
   <components>
${colourIds.map(({ id }) => `    <component objectid="${id}"/>`).join("\n")}
   </components>
  </object>`);
      items.push(`  <item objectid="${partId}"/>`);
      settings.push(`  <object id="${partId}">
    <metadata key="name" value="${name} — part ${idx + 1}"/>
    <metadata key="extruder" value="${palette.indexOf(colourIds[0].hex) + 1}"/>
${colourIds.map(({ id, hex }) => `    <part id="${id}" subtype="normal_part">
      <metadata key="name" value="${name} — part ${idx + 1} — ${hex}"/>
      <metadata key="extruder" value="${palette.indexOf(hex) + 1}"/>
    </part>`).join("\n")}
  </object>`);
    });

    const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02" xmlns:m="${M}">
 <metadata name="Application">BREPcode-${APP_VERSION}</metadata>
 <metadata name="Title">${name}</metadata>
 <resources>
  <m:colorgroup id="${COLOURS_ID}">
${palette.map((hex) => `   <m:color color="${hex}"/>`).join("\n")}
  </m:colorgroup>
${objects.join("\n")}
 </resources>
 <build>
${items.join("\n")}
 </build>
</model>
`;
    const config = `<?xml version="1.0" encoding="UTF-8"?>\n<config>\n${settings.join("\n")}\n</config>\n`;
    const project = `{\n  "filament_colour": [${palette.map((hex) => `"${hex}"`).join(", ")}]\n}\n`;
    return {
      suffix: plates.length > 1 ? `-plate${pi + 1}` : "",
      parts: placed.length,
      bytes: threeMfPackage(model, name, opts.source, [
        ["Metadata/model_settings.config", config],
        ["Metadata/project_settings.config", project],
      ]),
    };
  });
}

// Where the parametric source rides along inside an exported file. A mesh is a
// dead end — once a part leaves as triangles the recipe that made it is gone,
// and "I printed this a year ago and want it 3mm taller" means starting over.
// 3MF is a zip, so the source travels as its own plain-text part: readable with
// any unzip tool, ignored by every slicer, and enough to reopen the part as
// editable code. Keep the part name and marker stable — older files must keep
// loading.
export const SOURCE_PART = "Metadata/BREPcode.source.js";
export const SOURCE_MARKER = "BREPCODE-SOURCE-V1";

const sourceHeader = (name) =>
  `// ${SOURCE_MARKER}\n`
  + `// The BREPcode that generated "${name}". Paste it into BREPcode.com to get\n`
  + `// the editable, parametric model back — or just read it to see how it was made.\n`
  + `// Exported by BREPcode-${APP_VERSION}.\n\n`;

// The OPC wrapper both 3MF writers share. Every part in the package needs a
// declared content type, so the source brings its own Default. Slicers read
// 3D/3dmodel.model and ignore the rest — Bambu and Orca both ship extra
// Metadata/ parts of their own, so this is a well-trodden path, not a hack.
function threeMfPackage(model, name, code, extra = []) {
  const source = code ? String(code).trim() : "";
  const hasConfig = extra.some(([p]) => /\.config$/i.test(p));
  return storedZip([
    ["[Content_Types].xml", `<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
 <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
 <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>
${hasConfig ? ` <Default Extension="config" ContentType="application/xml"/>\n` : ""}${source ? ` <Default Extension="js" ContentType="text/javascript"/>\n` : ""}</Types>
`],
    ["_rels/.rels", `<?xml version="1.0" encoding="UTF-8"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
 <Relationship Target="/3D/3dmodel.model" Id="rel0" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>
</Relationships>
`],
    ["3D/3dmodel.model", model],
    ...(source ? [[SOURCE_PART, sourceHeader(name) + source + "\n"]] : []),
    // Slicer-side metadata, e.g. Metadata/model_settings.config — which is
    // where OrcaSlicer actually reads per-part colour from.
    ...extra,
  ]);
}

// ---------------------------------------------------------------- .bcode
//
// The project file: the one export that is the MODEL rather than a picture of
// it. Everything else here throws the recipe away and keeps the triangles;
// this keeps the recipe and can regenerate the triangles at any size.
//
// It exists because nothing in BREPcode saved your work. Theme, material,
// grid, model name and AI settings were all persisted — the CODE never was.
// Close the tab and it was gone.
//
// Deliberately PLAIN TEXT, not JSON. The source sits at the top exactly as you
// wrote it, so the file opens in Notepad and is directly editable, diffs
// cleanly in git, and can be pasted straight into the app. The scene and the
// undo history ride underneath in a block comment, which the app reads and
// everything else ignores. Hand-edit the source, mangle the comment, delete it
// entirely — the file still loads, because the source is the part that matters
// and the rest is decoration.
export const SCENE_OPEN = "/* BREPCODE-SCENE-V1";
export const SCENE_CLOSE = "BREPCODE-SCENE-END */";

// Undo history is capped: the in-app stack holds 200 full copies of the source,
// which on a real model is megabytes of near-identical text for something
// nobody scrolls back through. The most recent states are the useful ones.
export const HISTORY_KEEP = 40;

export function bcodeFile(source, meta = {}) {
  const src = String(source || "").trim();
  const name = String(meta.name || "brepcode-model").replace(/[\r\n]/g, " ");
  const scene = {};
  if (meta.scene) scene.scene = meta.scene;
  if (Array.isArray(meta.history) && meta.history.length) {
    scene.history = meta.history.slice(-HISTORY_KEEP).map((h) => String(h));
  }

  let out = `// ${SOURCE_MARKER}\n`
    + `// "${name}" — a BREPcode model, saved by BREPcode-${APP_VERSION}.\n`
    + `// This is plain text: edit the model below in any editor, or paste it\n`
    + `// into BREPcode.com. Opening this file in BREPcode restores it exactly.\n\n`
    + `${src}\n`;
  if (Object.keys(scene).length) {
    // Guard the delimiters: source containing the closing token would end the
    // comment early and spill JSON into the model. It cannot happen from the
    // source side (it sits above), but a scene value could carry anything.
    const json = JSON.stringify(scene, null, 1).split("*/").join("*\\/");
    out += `\n${SCENE_OPEN}\n${json}\n${SCENE_CLOSE}\n`;
  }
  return out;
}

// Split a .bcode file back into its parts. A file that is nothing but bare
// BREPcode — someone's hand-written model, or ours with the comment deleted —
// still parses: you get the source and no scene, which is the correct reading.
export function parseBcodeFile(text) {
  const t = String(text || "").replace(/^﻿/, "");
  let scene = null;
  let body = t;

  const open = t.indexOf(SCENE_OPEN);
  if (open >= 0) {
    // Cut the body at the marker whether or not the block ever closes. A file
    // truncated mid-write — interrupted download, full disk — has an opening
    // marker and no end, and keeping the whole text would have dropped raw JSON
    // into the editor as if it were part of the model.
    body = t.slice(0, open);
    const close = t.indexOf(SCENE_CLOSE, open);
    if (close > open) {
      try {
        scene = JSON.parse(t.slice(open + SCENE_OPEN.length, close).split("*\\/").join("*/"));
      } catch { scene = null; }      // a corrupted block must not cost the source
    }
  }
  return {
    source: stripSourceHeader(body),
    scene: scene?.scene ?? null,
    history: Array.isArray(scene?.history) ? scene.history : [],
  };
}

// The same idea for STL, which has no container at all — the source goes after
// `endsolid`, where a well-behaved reader stops.
//
// It is BASE64, not plain text, and that is deliberate: three.js's ASCII STL
// loader regex-scans the WHOLE file for `facet normal` blocks rather than
// stopping at endsolid. Source that happened to contain those words — a
// comment, a string, one of our own generated-STL examples — would inject
// phantom triangles into anything that reimported it. Base64 cannot collide
// with the grammar. The plain-English header above it says what it is.
export function stlWithSource(stl, code) {
  const source = code ? String(code).trim() : "";
  if (!source) return stl;
  const b64 = btoa(unescape(encodeURIComponent(source)));
  return `${stl.trimEnd()}\n${SOURCE_MARKER}\n`
    + "The BREPcode that generated this part, as base64 of UTF-8. Decode it and\n"
    + "paste it into BREPcode.com to get the editable, parametric model back.\n"
    + `${(b64.match(/.{1,76}/g) || []).join("\n")}\nEND-${SOURCE_MARKER}\n`;
}

// Take our own header off the 3MF source part, and nothing else. Stripping
// every `//` line instead — the obvious shortcut — silently ate the author's
// own comments on the way back in, which is a worse loss than the header.
export function stripSourceHeader(text) {
  const t = String(text || "").replace(/^﻿/, "");
  if (!t.startsWith(`// ${SOURCE_MARKER}`)) return t.trim();
  const gap = t.indexOf("\n\n");
  return (gap < 0 ? "" : t.slice(gap + 2)).trim();
}

// Pull it back out of an STL. Returns "" when there is none, which is the
// normal case for a file from anywhere else.
export function extractSourceFromStl(text) {
  const m = new RegExp(
    `${SOURCE_MARKER}\\n[\\s\\S]*?\\n((?:[A-Za-z0-9+/=]+\\n)+)END-${SOURCE_MARKER}`).exec(text);
  if (!m) return "";
  try { return decodeURIComponent(escape(atob(m[1].replace(/\s/g, "")))); }
  catch { return ""; }
}

export function stlTo3MF(stl, name = "brepcode-model", opts = {}) {
  const { verts, tris } = parseStlTriangles(stl);
  // Onto the middle of the plate rather than its front-left corner — see
  // plateOffset(). An empty mesh has no bounds worth moving.
  const [ox, oy, oz] = verts.length ? plateOffset(boundsOf(verts), opts.plate) : [0, 0, 0];
  // Core-spec metadata, so anything reading this file knows where it came from.
  // Our 3MF used to declare nothing at all, which is simply a gap.
  //
  // What this deliberately does NOT do is claim to be a slicer project.
  // OrcaSlicer greets a bare 3MF with "generated by an old OrcaSlicer version,
  // loading geometry data only", and the tempting fix — adding its
  // `BambuStudio:3mfVersion` marker — is a trap: it makes Orca take the Bambu
  // project path, then hunt for the per-object settings, plate thumbnails and
  // slice info that a real project carries. Measured, the file went from
  // loading in about 30 seconds to not loading at all. The message is also
  // accurate: we export geometry, and have no print settings to give it.
  const model = `<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xml:lang="en-US" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
 <metadata name="Application">BREPcode-${APP_VERSION}</metadata>
 <metadata name="Title">${name}</metadata>
 <resources>
  <object id="1" type="model" name="${name}">
   <mesh>
    <vertices>
${verts.map((v) => `     <vertex x="${+(+v[0] + ox).toFixed(5)}" y="${+(+v[1] + oy).toFixed(5)}" z="${+(+v[2] + oz).toFixed(5)}"/>`).join("\n")}
    </vertices>
    <triangles>
${tris.map((t) => `     <triangle v1="${t[0]}" v2="${t[1]}" v3="${t[2]}"/>`).join("\n")}
    </triangles>
   </mesh>
  </object>
 </resources>
 <build>
  <item objectid="1"/>
 </build>
</model>
`;
  return threeMfPackage(model, name, opts.source);
}
