// What a published page lets a visitor do.
//
// Two places need to agree about this and they are not in the same codebase:
// the editor, where the choice is made, and the published page, which has to
// honour it. Keeping the rules here means the page cannot drift into offering
// something the person who published it did not tick — and the sentence a
// publisher reads before they publish is generated by the same code that
// decides what the page actually shows.
//
// Nothing here is a security boundary. The .bcode is served to the page either
// way, so a determined visitor can always read it; these flags decide what the
// page OFFERS, which is a courtesy setting, not a lock. Anything that truly
// must not be handed out should not be published.

export const VISITOR_DEFAULTS = Object.freeze({
  orbit: true,    // spin and zoom, rather than a still thumbnail
  model: true,    // download STL / 3MF / STEP
  svg: false,     // download the 3-view drawing
  html: false,    // download a standalone self-contained page
  edit: true,     // open it back up in BREPcode
});

export const VISITOR_KEYS = Object.freeze(Object.keys(VISITOR_DEFAULTS));

// A stored value is whatever was written months ago by an older build, so
// every key is checked rather than trusted. A missing key takes the default,
// which is what makes a model published before these options existed keep
// behaving the way it did — absent is "not specified", not "forbidden".
export function normalizeVisitor(raw) {
  const out = {};
  for (const k of VISITOR_KEYS) {
    out[k] = typeof raw?.[k] === "boolean" ? raw[k] : VISITOR_DEFAULTS[k];
  }
  return out;
}

// Every box clear. Deliberately computed from the normalised value, so it
// cannot be reached by accident with a null or a stray {}.
export function isPreviewOnly(raw) {
  const v = normalizeVisitor(raw);
  return VISITOR_KEYS.every((k) => !v[k]);
}

const joinList = (parts) =>
  parts.length <= 1 ? (parts[0] || "")
    : `${parts.slice(0, -1).join(", ")} and ${parts[parts.length - 1]}`;

// The one sentence both sides show. Said in terms of what a VISITOR can do,
// because that is who the setting is about.
export function visitorSummary(raw) {
  const v = normalizeVisitor(raw);
  const can = [];
  if (v.orbit) can.push("spin it");
  if (v.model) can.push("download the model");
  if (v.svg) can.push("download the drawing");
  if (v.html) can.push("take a standalone page");
  if (v.edit) can.push("open it in BREPcode");
  return can.length
    ? `Visitors can ${joinList(can)}.`
    : "Preview only — visitors get the still thumbnail and nothing else.";
}
