// "Open this model in my slicer" — the thing a web page fundamentally cannot do.
//
// The browser can only hand you a downloaded .3mf. The desktop app can write the
// file and ask the OS to open it, which is one click instead of four.
//
// The awkward part is the version tag. OrcaSlicer greets any plain 3MF with
// "generated by an old OrcaSlicer version, loading geometry data only" before it
// will show anything — a known Orca bug that hits Fusion 360 and Onshape too.
// Measured, the accepted value is a WINDOW, not a floor: absent or too low gets
// "old version", too high gets "newer version", and only the installed build's
// own number opens silently. So the file has to name the version of the Orca
// that will open it, which means finding out what that is.
//
// Detection order matters, and the obvious source is the WORST one: on this very
// machine OrcaSlicer is installed with no uninstall registry entry at all, and
// its exe carries no version resource. What it does have is a config file that
// the running Orca wrote itself, which is about as authoritative as it gets.

// electron is required lazily inside register() so the detection below can be
// exercised by a plain node test — and by anyone debugging "why did it not find
// my slicer" — without booting an Electron app.
const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

// "02.05.01.52" -> "2.5.1". Orca zero-pads each field and appends a build
// number; the tag it compares against is the plain three-part version.
function tidyVersion(raw) {
  const parts = String(raw || "").trim().split(".").map((p) => String(parseInt(p, 10)));
  if (parts.length < 3 || parts.slice(0, 3).some((p) => p === "NaN")) return null;
  return parts.slice(0, 3).join(".");
}

const appDataRoot = () =>
  process.env.APPDATA || path.join(os.homedir(), "AppData", "Roaming");
const ORCA_DIRS = ["OrcaSlicer", "OrcaSlicer-nightly", "OrcaSlicer-dev", "OrcaSlicerNightly"];

// 1. What the running slicer PRINTED about itself, which is the only source
// that has ever been right.
//
// The obvious candidate — "version" in OrcaSlicer.conf — is a trap, and it cost
// a wrong answer in front of the user. That field is the settings/data format
// version: this machine's conf says 02.05.01.52 while the slicer is 2.4.0. We
// stamped 2.5.1 into the file and Orca answered "The 3MF file version 2.5.1 is
// newer than Orca Slicer's version 2.4.0-Nanashi", which is the WORSE of the
// two failure modes — a version that is too low still loads the geometry, one
// that is too high reads as a file the slicer cannot handle.
//
// The log says it plainly, on the first line of every run:
//   OrcaSlicer Version 2.4.0-Nanashi
// Only the numeric part goes into the 3MF; a fork's suffix is its own business.
function versionFromLog() {
  for (const name of ORCA_DIRS) {
    const dir = path.join(appDataRoot(), name, "log");
    let logs = [];
    try {
      logs = fs.readdirSync(dir)
        .map((f) => path.join(dir, f))
        .map((f) => { try { return { f, t: fs.statSync(f).mtimeMs }; } catch { return null; } })
        .filter(Boolean)
        .sort((a, b) => b.t - a.t)
        .slice(0, 5)                       // newest few; older ones can predate an update
        .map((x) => x.f);
    } catch { continue; }
    for (const file of logs) {
      try {
        // The banner is at the very top, so don't read a 50MB debug log whole.
        const fd = fs.openSync(file, "r");
        const buf = Buffer.alloc(65536);
        const n = fs.readSync(fd, buf, 0, buf.length, 0);
        fs.closeSync(fd);
        const m = /OrcaSlicer\s+Version\s+(\d+\.\d+\.\d+)/i.exec(buf.subarray(0, n).toString("utf8"));
        if (m) return m[1];
      } catch { /* locked or unreadable — try the next */ }
    }
  }
  return null;
}

// 2. The uninstall entries, for a normal installer install.
function fromRegistry() {
  const roots = [
    "HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall",
    "HKLM\\SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall",
    "HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall",
  ];
  for (const root of roots) {
    let out = "";
    try {
      out = execFileSync("reg", ["query", root, "/s", "/f", "Orca", "/t", "REG_SZ"],
        { encoding: "utf8", timeout: 8000, windowsHide: true });
    } catch { continue; }
    if (!/OrcaSlicer/i.test(out)) continue;
    const version = tidyVersion(/DisplayVersion\s+REG_SZ\s+(\S+)/i.exec(out)?.[1]);
    const loc = /InstallLocation\s+REG_SZ\s+(.+)/i.exec(out)?.[1]?.trim();
    const icon = /DisplayIcon\s+REG_SZ\s+(.+?)(?:,\d+)?\s*$/im.exec(out)?.[1]?.trim();
    const exe = [icon, loc && path.join(loc, "orca-slicer.exe")]
      .find((p) => p && /\.exe$/i.test(p) && exists(p));
    if (version || exe) return { version, exe };
  }
  return {};
}

const exists = (p) => { try { return fs.statSync(p).isFile(); } catch { return false; } };

// 3. Where it actually lands when nothing registered it.
function exeFromDisk() {
  const bases = [
    process.env.ProgramFiles, process.env["ProgramFiles(x86)"],
    process.env.LOCALAPPDATA && path.join(process.env.LOCALAPPDATA, "Programs"),
  ].filter(Boolean);
  for (const base of bases) {
    for (const dir of ["OrcaSlicer", "OrcaSlicer-nightly"]) {
      for (const exe of ["orca-slicer.exe", "OrcaSlicer.exe"]) {
        const full = path.join(base, dir, exe);
        if (exists(full)) return full;
      }
    }
  }
  return null;
}

function detect() {
  const reg = process.platform === "win32" ? fromRegistry() : {};
  // When we cannot work it out, stamp NOTHING. Guessing too high is worse than
  // saying nothing: too low (or absent) still loads the geometry with a notice,
  // too high reads as a file this slicer is not equipped to open.
  return {
    exe: reg.exe || exeFromDisk() || null,
    version: versionFromLog() || reg.version || null,
  };
}

function register() {
  const { ipcMain, shell } = require("electron");
  // The renderer asks BEFORE exporting, so it can stamp the right version into
  // the 3MF it is about to build.
  ipcMain.handle("slicer:info", () => {
    try {
      const d = detect();
      return { ok: true, found: !!d.exe, exe: d.exe, version: d.version };
    } catch (e) {
      return { ok: false, error: String(e?.message || e), found: false };
    }
  });

  // { name, base64 } -> writes a .3mf to temp and opens it.
  ipcMain.handle("slicer:open", async (_e, { name, base64 } = {}) => {
    try {
      if (!base64) return { ok: false, error: "nothing to open" };
      const stem = String(name || "model").replace(/[^\w.-]+/g, "_").slice(0, 60) || "model";
      const dir = path.join(os.tmpdir(), "BREPcode-slicer");
      fs.mkdirSync(dir, { recursive: true });
      const file = path.join(dir, `${stem}.3mf`);
      fs.writeFileSync(file, Buffer.from(base64, "base64"));

      const { exe } = detect();
      if (exe) {
        // Launch it directly rather than via the shell: the user may well have
        // .3mf associated with Bambu Studio or PrusaSlicer, and "open in Orca"
        // should open Orca.
        const { spawn } = require("node:child_process");
        spawn(exe, [file], { detached: true, stdio: "ignore", windowsHide: false }).unref();
        return { ok: true, file, via: "orca" };
      }
      // No Orca: hand it to whatever the OS uses for .3mf. Still one click.
      const err = await shell.openPath(file);
      if (err) return { ok: false, error: err, file };
      return { ok: true, file, via: "default app" };
    } catch (e) {
      return { ok: false, error: String(e?.message || e) };
    }
  });
}

module.exports = { register, detect, tidyVersion };
